name: LootConomy
main: su.nightexpress.lootconomy.LootConomyPlugin
version: '${project.version}'
api-version: 1.21
folia-supported: true
description: Spread your economy & currencies across the world in a natural way!
author: NightExpress
depend:
  - nightcore
  - EconomyBridge
softdepend:
  - MythicMobs
  - PlaceholderAPI
